{% set name = "oracle-ads" %}
{% set version = "2.12.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oracle_ads-{{ version }}.tar.gz
  sha256: 8dd978f0dc6b7e6134413f0f87423d0b9963447d885dbd200199002d295cee5b

build:
  noarch: python
  entry_points:
    - ads = ads.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.8,<4
    - pip
  run:
    - pydantic >=2.6.3
    - python >=3.8
    - pyyaml >=6
    - asteval >=0.9.25
    - cerberus >=1.3.4
    - cloudpickle >=1.6.0
    - fire
    - fsspec >=0.8.7
    - gitpython >=3.1.2
    - jinja2 >=2.11.2
    - matplotlib-base >=3.1.3,<=3.8.4
    - numpy >=1.19.2,<2.0.0
    - oci >=2.125.3
    - ocifs >=1.1.3
    - pandas >1.2.1
    - psutil >=5.7.2
    - python_jsonschema_objects >=0.3.13
    - requests
    - scikit-learn >=1.0
    - tabulate >=0.8.9
    - tqdm >=4.59.0

test:
  imports:
    - ads
  commands:
    - pip check
    - ads --help
  requires:
    - pip

about:
  summary: Oracle Accelerated Data Science SDK
  home: https://github.com/oracle/accelerated-data-science
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
