{% set name = "oracle-ads" %}
{% set version = "2.13.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oracle_ads-{{ version }}.tar.gz
  sha256: 9b7665f99815a748a6129c3d7fe5f8799fd0828885651ef192d3ca9fe6df6fef

build:
  noarch: python
  entry_points:
    - ads = ads.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.8,<4
    - pip
  run:
    - httpx
    - tenacity
    - pydantic >=2.6.3
    - python >={{ python_min }}
    - pyyaml >=6.0.1
    - asteval >=0.9.25
    - cerberus >=1.3.4
    - cloudpickle >=1.6.0
    - fire
    - fsspec >=0.8.7
    - gitpython >=3.1.2
    - jinja2 >=2.11.2
    - matplotlib-base >=3.1.3
    - numpy >=1.19.2
    - oci >=2.148.0
    - ocifs >=1.1.3
    - pandas >=2.2.0
    - psutil >=5.7.2
    - python_jsonschema_objects >=0.3.13
    - requests
    - scikit-learn >=1.0
    - tabulate >=0.8.9
    - tqdm >=4.59.0

test:
  imports:
    - ads
  commands:
    - pip check
    - ads --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Oracle Accelerated Data Science SDK
  home: https://github.com/oracle/accelerated-data-science
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
