schema_version: 1

context:
  name: oracle-ads
  version: "2.16.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/oracle_ads-${{ version }}.tar.gz
  sha256: 8ef472154ea21b9e54f14ed604cc5a5ea59c285bfab472c1045fcd7a1d5ed562

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - ads = ads.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.8,<4
    - pip
  run:
    - packaging >=21.0
    - httpx
    - tenacity
    - pydantic >=2.6.3
    - python >=${{ python_min }}
    - pyyaml >=6.0.1
    - asteval >=0.9.25
    - cerberus >=1.3.4
    - cloudpickle >=1.6.0
    - fire
    - fsspec >=0.8.7
    - gitpython >=3.1.2
    - jinja2 >=2.11.2
    - matplotlib-base >=3.1.3
    - numpy >=1.19.2
    - oci >=2.148.0
    - ocifs >=1.1.3
    - pandas >=2.2.0,<3.0.0
    - psutil >=5.7.2
    - python_jsonschema_objects >=0.3.13
    - requests
    - scikit-learn >=1.0
    - tabulate >=0.8.9
    - tqdm >=4.59.0
    - rich

tests:
  - python:
      imports:
        - ads
      pip_check: true
      python_version: ${{ python_min }}
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - ads --help

about:
  summary: Oracle Accelerated Data Science SDK
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/oracle/accelerated-data-science

extra:
  recipe-maintainers:
    - jan-janssen
